[s3]
column='text'
key="" 
secret=""
output_dir='composed_datasets'
output_bucket = "hyde-data-preprocessed"

[[sources]]
bucket="hyde-data-normalized"
paths = ["Juris/*", "Beck Aktuell/*"]
[[sources]]
bucket="hyde-data-preprocessed"
paths = ["Court_decisions/*", "Legal_laws/*"]

[composition]
train=0.7